import { Type, type Static } from "@sinclair/typebox";

/**
 * Shared primitives. Every route schema builds on these so that formats stay
 * consistent across the REST API, the generated OpenAPI document and the
 * frontend client types.
 */

/**
 * Primary keys are UUIDv7 generated by PostgreSQL. Time-ordered, so they sort
 * chronologically and keep index inserts local.
 */
export const Uuid = Type.String({
  format: "uuid",
  description: "UUIDv7 identifier.",
});

/** All timestamps cross the API as UTC ISO 8601. Clients localise for display. */
export const Timestamp = Type.String({
  format: "date-time",
  description: "UTC timestamp, ISO 8601.",
});

export const NullableTimestamp = Type.Union([Timestamp, Type.Null()]);

export const PaginationQuery = Type.Object({
  limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 100, default: 50 })),
  cursor: Type.Optional(
    Type.String({ description: "Opaque cursor from a previous page." }),
  ),
});
export type PaginationQuery = Static<typeof PaginationQuery>;

export function PaginatedResponse<T extends ReturnType<typeof Type.Object>>(item: T) {
  return Type.Object({
    items: Type.Array(item),
    nextCursor: Type.Union([Type.String(), Type.Null()], {
      description: "Pass as `cursor` to fetch the next page. Null when exhausted.",
    }),
  });
}
