import { createReadStream } from "node:fs";
import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve, sep } from "node:path";

/**
 * Files on disk.
 *
 * Storage keys are generated by `storageKeyFor` and never derived from an
 * uploaded name, so nothing here should ever see a traversal attempt. It is
 * checked anyway: this is the one place where being wrong means writing
 * outside the data directory, and a check that can only ever pass costs
 * nothing to keep.
 */
export class AttachmentStore {
  private readonly root: string;

  constructor(root: string) {
    this.root = resolve(root);
  }

  private pathFor(storageKey: string): string {
    const full = resolve(join(this.root, storageKey));

    // `resolve` collapses "..", so a key that escapes the root is visible here
    // and nowhere later.
    if (full !== this.root && !full.startsWith(this.root + sep)) {
      throw new Error(`Storage key escapes the attachment root: ${storageKey}`);
    }

    return full;
  }

  async write(storageKey: string, bytes: Uint8Array): Promise<void> {
    const path = this.pathFor(storageKey);
    await mkdir(dirname(path), { recursive: true });
    // `wx` fails rather than overwrites. Keys are uuids, so a collision means
    // something is wrong that silently replacing somebody's file would hide.
    await writeFile(path, bytes, { flag: "wx" });
  }

  read(storageKey: string): NodeJS.ReadableStream {
    return createReadStream(this.pathFor(storageKey));
  }

  async exists(storageKey: string): Promise<boolean> {
    try {
      await stat(this.pathFor(storageKey));
      return true;
    } catch {
      return false;
    }
  }

  /** Used by the sweep. Missing is success: the goal is for it to be gone. */
  async remove(storageKey: string): Promise<void> {
    await rm(this.pathFor(storageKey), { force: true });
  }
}
